motor_info:
        min_pwm: 0.5 # 1000 ~ dshot 0
        max_pwm: 0.9 # 1800 ~ dshot 1600
        min_thrust: 0.0 # [N]
        force_landing_thrust: 6.0 # [N]

        # these two parameters are from u=25.2v_down_prop_w_mount_part_motor_test_1727860665.txt
        krpm_square_to_thrust_ratio: 0.1283  # N/(kRPM)^2
        krpm_square_to_thrust_bias: -0.3572  # N
        rotor_damping_rate: 0.1062 # = dt/t_thrust = 0.01 (guess) / 0.0942
        m_f_rate: -0.0165 # (-0.0166 + -0.0165 + -0.0166 +  -0.0164 + -0.0162) / 5 = -0.0165

        pwm_conversion_mode: 1 # POLYNOMIAL Mode
        # Note that for SQRT mode, only poly2 is 10x, others are 1x, and the relationship is fz = f(pwm).
        # But for POLYNOMIAL mode, the coefficients are 10x one by one, and the relationship is pwm = f(fz).
        # Specifically, get the coefficients from aerial_robot_nerve/motor_test/scripts/analyze_data.py, the second group.
        # SQRT Mode ref: https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp#L825
        # POLYNOMIAL Mode ref: https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp#L832
        vel_ref_num: 5
        ref1:
                voltage: 25.2 # [V]
                max_thrust: 18.0750 # N
                polynominal4: 1.46730692  # x10^4
                polynominal3: -14.36655551  # x10^3
                polynominal2: 29.78253140  # x10^2
                polynominal1: 3.77009528  # x10^1
                polynominal0: 54.85807505  # x10^0

        ref2:
                voltage: 24.20 # [V]
                max_thrust: 18.5398 # N
                polynominal4: 4.41630103  # x10^4
                polynominal3: -24.96489103  # x10^3
                polynominal2: 40.83097780  # x10^2
                polynominal1: 2.04240478  # x10^1
                polynominal0: 54.95776399  # x10^0

        ref3:
                voltage: 23.20 # [V]
                max_thrust: 18.9598 # N
                polynominal4: 6.36105924  # x10^4
                polynominal3: -31.62690016  # x10^3
                polynominal2: 46.87143537  # x10^2
                polynominal1: 2.51549499  # x10^1
                polynominal0: 54.94123093  # x10^0

        ref4:
                voltage: 22.20 # [V]
                max_thrust: 17.3809 # N
                polynominal4: 10.22625163  # x10^4
                polynominal3: -43.08813930  # x10^3
                polynominal2: 55.66088615  # x10^2
                polynominal1: 3.66116634  # x10^1
                polynominal0: 54.38660586  # x10^0

        ref5:
                voltage: 21.20 # [V]
                max_thrust: 16.2076 # N
                polynominal4: 16.38556727  # x10^4
                polynominal3: -63.49447426  # x10^3
                polynominal2: 76.36731629  # x10^2
                polynominal1: -0.84126732  # x10^1
                polynominal0: 54.78809463  # x10^0

